# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 114be2b0a7b1c46b9502ff0f80ffe877b29c5dad7a49f1dd20ea3a8822711d4c2f018da534fcf9e74959c0658b96c889cad5b38f9c0ed5882b57bc34ce66be84

test:
  secret_key_base: ce424d2129f624b8db24187b37e128951d227cb4a1d336afaa2e2e957c4a0ce6a400f7733e30001c07f4718ff212e64fbdc47c351587bd560f0192ca0cb321bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
